config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwards], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwards], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "privacy" => "homes#privacy", as:"privacy"
  get "terms" => "homes#terms", as:"terms"
  get 'search_result', to: 'searches#search_result', as: 'search_result'

  resources :parties, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :like, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    get 'liked_parties', on: :member
  end

  namespace :admin do
    resources :weapons
    resources :users, only: [:index,:destroy]
    resources :comments, only: [:index, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

end

app/models/party.rb
class Party < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :party_weapons, dependent: :destroy
  has_many :weapons, through: :party_weapons
  accepts_nested_attributes_for :weapons
  accepts_nested_attributes_for :party_weapons, allow_destroy: true
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy


  has_many :partytags
  has_many :tags, through: :partytags
  accepts_nested_attributes_for :tags

  attr_accessor :new_tags

  def likes_count
    likes.count
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def likes?(party)
    likes.exists?(party_id: party.id) if party
  end

  def self.search_by_name(query)
    where("name LIKE ?", "%#{query}%")
  end

    GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.display_name = "guestuser"
      user.introduction = "ゲストログイン中"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def guest?
    false
  end


end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController

  def new
    @party = Party.new
    @weapons = Weapon.all
  end

  def create
    @party = Party.new(party_params)
    @party.user = current_user

    tag_ids = params[:party][:tag_ids].reject(&:blank?)
    new_tags = params[:party][:new_tags].split(',').map(&:strip)

    tag_ids += new_tags.map { |tag_name| Tag.find_or_create_by(name: tag_name).id }
    @party.tag_ids = tag_ids

    if @party.save
      redirect_to @party, notice: '新しい編成が作成されました。'
    else
      puts @party.errors.full_messages
      @weapons = Weapon.all
      render :new
    end
  end

  def index
    @parties = Party.page(params[:page]) || []
  end

  def edit
    @party = Party.find(params[:id])
    @weapons = Weapon.all
  end

  def update
    @party = Party.find(params[:id])
    if @party.update(party_params)
      redirect_to party_path(@party), notice: '記事が更新されました'
    else
      render :edit
    end
  end

  def show
    @party = Party.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    party = Party.find(params[:id])
    party.destroy
    redirect_to '/party'
  end

  private

  def party_params
    params.require(:party).permit(:name,
                                  :introduction,
                                  :image,
                                  :turn_number,
                                  :enemy_defence,
                                  :airship,
                                  :reactor,
                                  :weekness,
                                  :attacks,
                                  :remainding_hp,
                                  :own_summon_type,
                                  :own_summon_buff,
                                  :friend_summon_type,
                                  :friend_summon_buff,
                                  :weapon_id,
                                  :new_tags,
                                  tag_ids: [], new_tags: [],
                                  party_weapons_attributes: [:id, :weapon_id, :_destroy],
                                  weapons_attributes: [
                                    :id, :weapon_id, :_destroy,
                                    :name, :attack, :hitpoint, :element, :weapontype,
                                    :optimus_might, :optimus_betrayal, :preemptive, :mutinys, :bahamut,
                                    :optimus_enmity, :zeal_enmity, :optimus_stamina, :strength_stamina,
                                    :omega_might, :omega_betrayal, :omega_enmity, :omega_stamina,
                                    :ex_might, :ex_might_sp, :eclipse, :optimus_verity, :omega_verity]
                                    )
  end

end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
<%= form_with model:party,local:true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control party_name' %>
  </div>
  <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: 'form-control party_introduction' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/parties/_index.html.erb
<div class="row mt-4">
  <% @parties.each do |f| %>
    <div class="col-12 col-md-6 col-lg-4 col-xl-3 mb-3">
      <div class="card">
        <div class="card-body">
          <h6 class="card-title"><%= link_to f.name, f %></h6>
          <h6 class="card-title"><%= f.introduction %></h6>
          <% unless user_signed_in? && current_user.guest? %>
            <div class="mt-3">
              <%= render 'shared/like_btn', f: f, party: f %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/parties/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
    <h3 class="mb-4">編成を編集する</h3>
    </div>
    <div class="col-md-5">


      <%= form_with(model: @party, url: party_path(@party), method: :patch) do |form| %>

        <div class="section mb-4">
          <h4>1. パーティの名前と説明文</h4>
          <%= form.label :name, 'パーティ名' %>
          <%= form.text_field :name, class: 'form-control' %>

          <%= form.label :introduction, '説明文' %>
          <%= form.text_area :introduction, class: 'form-control' %>
        </div>

        <div class="section mb-4">
          <h4>2. 敵キャラクターの防御値や属性相性</h4>
          <div class="row">
            <div class="col-md-6">
              <%= form.label :enemy_defence, '敵キャラクターの防御値' %>
              <%= form.number_field :enemy_defence, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :weakness, '敵キャラクターの属性相性' %>
              <%= form.select :weekness, ['有利', '不利', 'その他'], { prompt: '選択してください' }, class: 'form-control' %>
            </div>
          </div>
        </div>

        <div class="section mb-4">
          <h4>3. 騎空艇や炉のバフ</h4>
          <div class="row">
            <div class="col-md-6">
              <%= form.label :airship, '騎空艇のバフ' %>
              <%= form.select :airship, ['1.10',
                                         '1.09',
                                         '1.08',
                                         '1.07',
                                         '1.06',
                                         '1.05',
                                         '1.04',
                                         '1.03',
                                         '1.02',
                                         '1.00'],
                                         { prompt: '選択してください' }, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :reactor, '炉のバフ' %>
              <%= form.select :reactor, ['1.10',
                                         '1.07',
                                         '1.05',
                                         '1.00'],
                                         { prompt: '選択してください' }, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="section mb-4">
          <h4>4. 召喚石の加護</h4>
          <div class="row">
            <div class="col-md-6">
              <%= form.label :own_summon_type, '自身の召喚石の種類' %>
              <%= form.select :own_summon_type, ['神', 'マグナ', '属性'], { prompt: '選択してください' }, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :own_summon_buff, '自身の召喚石の加護' %>
              <%= form.number_field :own_summon_buff, class: 'form-control', step: 5, min: 0 %>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-md-6">
              <%= form.label :friend_summon_type, 'フレンドの召喚石の種類' %>
              <%= form.select :friend_summon_type, ['神', 'マグナ', '属性'], { prompt: '選択してください' }, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :friend_summon_buff, 'フレンドの召喚石の加護' %>
              <%= form.number_field :friend_summon_buff, class: 'form-control', step: 5, min: 0 %>
            </div>
          </div>
        </div>
        <div class="section mb-4">
          <h4>5. タグの作成</h4>
          <div class="row">
            <div class="col-md-6">
              <%= form.label :tag_ids, 'タグ' %>
              <%= form.collection_select :tag_ids, Tag.all, :id, :name, { prompt: '選択してください' }, multiple: true, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :new_tags, '新しいタグ（カンマ区切り）' %>
              <%= form.text_field :new_tags, class: 'form-control' %>
            </div>
          </div>
        </div>
        <%= form.submit '更新する', class: 'btn btn-secondary' %>
    </div>

     <div class="col-md-5 offset-md-1">
      <div class="section mb-4">
        <h4>武器編成</h4>

        <!-- Bootstrapのフォーム要素を追加 -->
        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/parties/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h4>ユーザー情報</h4>
      <%= render 'users/info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h4>編成一覧</h4>
      <%= render 'index', parties: @parties %>
    </div>
  </div>
</div>

app/views/parties/like.js.erb
$('#like_btn').html("<%= escape_javascript(render('shared/like_btn', party: @party)) %>");

app/views/parties/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">
    <h3 class="mb-4">新しい編成を作成する</h3>
    </div>
    <div class="col-md-5">


      <%= form_with(model: @party, url: parties_path, method: :post) do |form| %>

        <div class="section mb-4">
          <h4>1. パーティの名前と説明文</h4>
          <%= form.label :name, 'パーティ名' %>
          <%= form.text_field :name, class: 'form-control' %>

          <%= form.label :introduction, '説明文' %>
          <%= form.text_area :introduction, class: 'form-control' %>
        </div>

        <div class="section mb-4">
          <h4>2. 敵キャラクターの防御値や属性相性</h4>
          <div class="row">
            <div class="col-md-6">
              <%= form.label :enemy_defence, '敵キャラクターの防御値' %>
              <%= form.number_field :enemy_defence, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :weakness, '敵キャラクターの属性相性' %>
              <%= form.select :weekness, ['有利', '不利', 'その他'], { prompt: '選択してください' }, class: 'form-control' %>
            </div>
          </div>
        </div>

        <div class="section mb-4">
          <h4>3. 騎空艇や炉のバフ</h4>
          <div class="row">
            <div class="col-md-6">
              <%= form.label :airship, '騎空艇のバフ' %>
              <%= form.select :airship, ['1.10',
                                         '1.09',
                                         '1.08',
                                         '1.07',
                                         '1.06',
                                         '1.05',
                                         '1.04',
                                         '1.03',
                                         '1.02',
                                         '1.00'],
                                         { prompt: '選択してください' }, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :reactor, '炉のバフ' %>
              <%= form.select :reactor, ['1.10',
                                         '1.07',
                                         '1.05',
                                         '1.00'],
                                         { prompt: '選択してください' }, class: 'form-control' %>
            </div>
          </div>
        </div>
        <div class="section mb-4">
          <h4>4. 召喚石の加護</h4>
          <div class="row">
            <div class="col-md-6">
              <%= form.label :own_summon_type, '自身の召喚石の種類' %>
              <%= form.select :own_summon_type, ['神', 'マグナ', '属性'], { prompt: '選択してください' }, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :own_summon_buff, '自身の召喚石の加護' %>
              <%= form.number_field :own_summon_buff, class: 'form-control', step: 5, min: 0 %>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-md-6">
              <%= form.label :friend_summon_type, 'フレンドの召喚石の種類' %>
              <%= form.select :friend_summon_type, ['神', 'マグナ', '属性'], { prompt: '選択してください' }, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :friend_summon_buff, 'フレンドの召喚石の加護' %>
              <%= form.number_field :friend_summon_buff, class: 'form-control', step: 5, min: 0 %>
            </div>
          </div>
        </div>
        <div class="section mb-4">
          <h4>5. タグの作成</h4>
          <div class="row">
            <div class="col-md-6">
              <%= form.label :tag_ids, 'タグ' %>
              <%= form.collection_select :tag_ids, Tag.all, :id, :name, { prompt: '選択してください' }, multiple: true, class: 'form-control' %>
            </div>
            <div class="col-md-6">
              <%= form.label :new_tags, '新しいタグ（カンマ区切り）' %>
              <%= form.text_field :new_tags, class: 'form-control' %>
            </div>
          </div>
        </div>
        <%= form.submit '作成する', class: 'btn btn-primary' %>
    </div>

     <div class="col-md-5 offset-md-1">
      <div class="section mb-4">
        <h4>武器編成</h4>

        <!-- Bootstrapのフォーム要素を追加 -->
        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>

        <div class="mb-4 input-group">
          <div class="input-group-prepend">
            <label class="input-group-text" for="weapon_id">武器選択</label>
          </div>
          <%= form.select :weapon_id, @weapons.map { |weapon| [weapon.name, weapon.id] }, { prompt: '選択してください' }, class: 'custom-select' %>
        </div>
        <%= form.fields_for :party_weapons do |pw_form| %>
          <div class="mb-4 input-group">
            <div class="input-group-prepend">
              <label class="input-group-text" for="party_weapon_weapon_id">武器選択</label>
            </div>
            <%= pw_form.collection_select :weapon_id, @weapons, :id, :name, { prompt: '選択してください' }, class: 'custom-select' %>
            <%= pw_form.check_box :_destroy, class: 'form-check-input' %>
            <%= pw_form.label :_destroy, '削除', class: 'form-check-label' %>
          </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/parties/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h4>ユーザー情報</h4>
      <%= render 'users/info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h4>編成の詳細</h4>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@party.user) do %>
            <%= image_tag @party.user.get_profile_image, size:"100x100" %><br>
            <%= @party.user.display_name %>
            <% end %>
          </td>
          <td><%= link_to @party.name, @party %></td>
          <td><%= @party.introduction %></td>
          <% if user_signed_in? && current_user == @party.user %>
            <td><%= link_to '編集', edit_party_path(@party), class: 'edit-button' %></td>
          <% end %>
        </tr>
      </table>

      <p><strong>敵キャラクターの防御値:</strong> <%= @party.enemy_defence %></p>
      <p><strong>属性相性:</strong> <%= @party.weekness %></p>
      <p><strong>騎空艇のバフ:</strong> <%= @party.airship %></p>
      <p><strong>炉のバフ:</strong> <%= @party.reactor %></p>
      <p><strong>召喚石:</strong> <%= @party.own_summon_type %>　加護：<%= @party.own_summon_buff %>％</p>
      <p><strong>フレンド召喚石:</strong> <%= @party.friend_summon_type %>　加護：<%= @party.friend_summon_buff %>％</p>

      <p><strong>編成タグ:</strong>
        <% @party.tags.each do |tag| %>
          <%= tag.name %>
        <% end %>
      </p>

      <div class="comments-index">
        <%= render "comments/index", party: @party %>
      </div>

      <%= render "comments/form", party: @party, comment: @comment %>

    </div>
  </div>
</div>

app/views/parties/unlike.js.erb
$('#like_btn').html("<%= escape_javascript(render('shared/like_btn', party: @party)) %>");