config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwards], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwards], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "privacy" => "homes#privacy", as:"privacy"
  get "terms" => "homes#terms", as:"terms"
  get 'search_result', to: 'searches#search_result', as: 'search_result'

  resources :parties, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :like, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    get 'liked_parties', on: :member
  end

  namespace :admin do
    resources :weapons
    resources :users, only: [:index,:destroy]
    resources :comments, only: [:index, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :party
  
end

app/controllers/admin/comments_controller.rb
class Admin:: CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to party_path(params[:party_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @party = Party.find(params[:party_id])
    @comments = @party.comments
  end

  def create
    party = Party.find(params[:party_id])
    comment = current_user.comments.new(comment_params)
    comment.party_id = party.id
    comment.save
    redirect_to party_path(party)
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to party_path(params[:party_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_counter.html.erb
コメント数: <%= party.comment.count %>

app/views/comments/_form.html.erb
<%= form_with(model:[party, comment], local: false) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100 comment-textarea" %>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/comments/_index.html.erb
<table>
  <tbody>
      <% party.comments.each do |f| %>
      <tr>

        <td>
          <%= link_to user_path(f.user) do %>
            <%= image_tag f.user.get_profile_image, size: "100x100" %><br>
            <%= f.user.display_name %>
          <% end %>
        </td>
        <td><%= f.comment %></td>
        <td>
          <% if f.user == current_user %>
            <%= link_to "削除する", party_comment_path(party, f), method: :delete, class: "btn btn-danger pull-right", remote: true %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/comments/create.js.erb
$('.comment-textarea').val("")
$('.comments-counter').html("<%= j(render 'comments/counter', party: @comment.party) %>")
$('.comments-index').html("<%= j(render 'comments/index', party: @comment.party) %>")

app/views/comments/destroy.js.erb
$('.comments-counter').html("<%= j(render 'comments/counter', party: @comment.party) %>")
$('.comments-index').html("<%= j(render 'comments/index', party: @comment.party) %>")