config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwards], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwards], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "privacy" => "homes#privacy", as:"privacy"
  get "terms" => "homes#terms", as:"terms"
  get 'search_result', to: 'searches#search_result', as: 'search_result'

  resources :parties, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :like, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    get 'liked_parties', on: :member
  end

  namespace :admin do
    resources :weapons
    resources :users, only: [:index,:destroy]
    resources :comments, only: [:index, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search_result
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]

    if @model == 'party'
      @records = Party.search_by_name(@content)
    elsif @model == 'tag'
      @records = Tag.search_by_name(@content)
    end
  end
end

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_tag search_result_path, method: :get do %>
    <%= text_field_tag :content, @content, placeholder: "検索キーワードを入力してください" %>
    <%= select_tag :model, options_for_select(['Party', 'Tag'], @model), prompt: "モデルを選択してください" %>
    <%= select_tag :method, options_for_select(['完全一致', '部分一致'], @method), prompt: "検索方法を選択してください" %>
    <%= submit_tag "検索" %>
  <% end %>
<% end %>

app/views/searches/search_result.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-12">

      <h3><%= @model.capitalize %>検索結果 for "<%= @content %>"</h3>

     <% if @model == 'party' %>
        <div>
          <h4>Party Results:</h4>
          <% @records.each do |party| %>
            <p><%= link_to party.name, party %></p>
          <% end %>
        </div>
      <% elsif @model == 'tag' %>
        <div>
          <h4>Tag Results:</h4>
          <% @records.each do |tag| %>
            <p><%= link_to tag.name, tag %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>